#### Naive Bayes
It is a probablistic classifier that is often when you have multi classes in which you want to place your data. This algorithm is particularly used when you deal with text classification with large data set and many features

In [28]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split

In [29]:
dataset = pd.read_csv("titanic.csv")
dataset = dataset.drop(columns=["PassengerId","Ticket","Embarked","Cabin","Name","SibSp","Parch"])
dataset.head()

   Survived  Pclass     Sex   Age     Fare
0         0       3    male  34.5   7.8292
1         1       3  female  47.0   7.0000
2         0       2    male  62.0   9.6875
3         0       3    male  27.0   8.6625
4         1       3  female  22.0  12.2875

In [30]:
dataset["Sex"] = dataset["Sex"].astype("category")
dataset["Sex"] = dataset["Sex"].cat.codes

dataset.head()

   Survived  Pclass  Sex   Age     Fare
0         0       3    1  34.5   7.8292
1         1       3    0  47.0   7.0000
2         0       2    1  62.0   9.6875
3         0       3    1  27.0   8.6625
4         1       3    0  22.0  12.2875

In [31]:
dataset = dataset.dropna()

In [32]:
y = dataset["Survived"]
X = dataset.drop(columns=["Survived"])

In [33]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=.2,random_state=42)

In [34]:
model = GaussianNB()

In [35]:
model.fit(X_train,y_train)

GaussianNB()

In [36]:
y_predict = model.predict(X_test)

In [37]:
model.score(X_train,y_train)

1.0

In [38]:
model.score(X_test,y_test)

1.0

In [39]:
y_predict

array([0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0], dtype=int64)

In [40]:
y_probability = model.predict_proba(X_test)