#### Basket Analysis
I want ot Apriori on Basket data of different customers

In [1]:
from mlxtend.frequent_patterns import apriori, association_rules
from mlxtend.preprocessing import TransactionEncoder
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

### basket Preprocessing

In [2]:
basket = pd.read_csv("../data/basket.csv")
basket.shape

(62141, 2)

In [3]:
basket.head()

   Member   Description
0  M09736  Other Sauces
1  M09736       Cashews
2  M09736    Other Dals
3  M09736       Namkeen
4  M09736         Sugar

In [4]:
basket[basket["Member"] == "M09736"]

     Member       Description
0    M09736      Other Sauces
1    M09736           Cashews
2    M09736        Other Dals
3    M09736           Namkeen
4    M09736             Sugar
..      ...               ...
621  M09736             Beans
622  M09736   Root Vegetables
623  M09736   Root Vegetables
624  M09736            Banana
625  M09736  Other Vegetables

[626 rows x 2 columns]

In [5]:
basket["Description"] = basket["Description"].str.strip()

In [6]:
basket.dropna(axis=0,subset=["Member"],inplace=True) # remove duplicate invoice number
basket.head()

   Member   Description
0  M09736  Other Sauces
1  M09736       Cashews
2  M09736    Other Dals
3  M09736       Namkeen
4  M09736         Sugar

#### Data Encoding
Convert data rows into columns. 
1. Each unique item in the description is a column or item that the customer have purchased.
2. Check the rows to find if this item is purchased or not.
3. If this item is purchased set it to 1 else 0

In [7]:
members = basket["Member"].unique()
members

array(['M09736', 'M39021', 'M47229', 'M76390', 'M77779', 'M78365',
       'M78720', 'M82651', 'M84827', 'M86304', 'M86572', 'M90375',
       'M91098', 'M96365', 'M99030', 'M99206', 'M04158', 'M08075',
       'M09303', 'M12050', 'M12127', 'M14746', 'M16218', 'M16611',
       'M18732', 'M22037', 'M25900', 'M27458', 'M27871', 'M31101',
       'M31908', 'M31966', 'M32039', 'M32409', 'M32449', 'M32480',
       'M32655', 'M33064', 'M33422', 'M33491', 'M33558', 'M33745',
       'M33767', 'M34566', 'M35070', 'M35464', 'M35538', 'M35649',
       'M36366', 'M36432', 'M36702', 'M36876', 'M37253', 'M37600',
       'M38622', 'M40184', 'M41700', 'M41747', 'M41781', 'M42182',
       'M42513', 'M42827', 'M43189', 'M43831', 'M43977', 'M44156',
       'M45375', 'M45470', 'M46325', 'M46328', 'M46575', 'M46687',
       'M48101', 'M48154', 'M48938', 'M50038', 'M50094', 'M50420',
       'M50767', 'M51043', 'M51278', 'M52629', 'M54100', 'M54345',
       'M54382', 'M54619', 'M54796', 'M55932', 'M56255', 'M56309',
       'M56368', 'M56489', 'M56516', 'M56897', 'M57093', 'M57327',
       'M57354', 'M58761', 'M58939', 'M59012', 'M59232', 'M62656',
       'M62833', 'M63404', 'M64055', 'M64379'], dtype=object)

In [8]:
set_columns = basket["Description"].unique()
set_columns

array(['Other Sauces', 'Cashews', 'Other Dals', 'Namkeen', 'Sugar',
       'Banana', 'Sugar Cubes', 'Other Sweets', 'Other Rice Products',
       'Utensil Scrub Pads', 'Toor Dal', 'Buns & Pavs', 'Cakes',
       'Boiled Rice', 'Urad Dal', 'Jaggery', 'Raisins', 'Chips',
       'Almonds', 'Root Vegetables', 'Other Vegetables', 'Moong Dal',
       'Healthy Snacks', 'Raw Peanuts', 'Mosquito Repellent',
       'Whole Spices', 'Soya Products', 'Beans', 'Health Drinks',
       'Liquid Soaps & Bars', 'Washing Bars', 'Ghee', 'Organic F&V',
       'Sunflower Oils', 'Shoe Polish', 'Cream Biscuits', 'Cookies',
       'Snacky Nuts', 'Avalakki / Poha', 'Besan', 'Raw Rice',
       'Powdered Spices', 'Eggs', 'Corn Snacks', 'Bread',
       'Instant Noodles', 'Sooji & Rava', 'Gourd & Cucumber',
       'Shaving Cream, Foam & Gels', 'Brinjals', 'Hair Oil',
       'Ground Coffee', 'Other Dry Fruits', 'Basmati Rice', 'Face Wash',
       'Yogurt & Lassi', 'Wafers', 'Instant Pastas', 'Cooking Paste',
       'Other Flours', 'Shaving Brush', 'Chilli & Soya Sauces',
       'Vermicelli', 'Glucose, Marie & Milk Biscuits', 'Diapers & Wipes',
       'Tomato Ketchup', 'Organic Rice & Rice Products', 'Other Oils',
       'Hair Conditioner', 'Other Insect Repellent', 'Cut Vegetables',
       'Health Supplements', 'Other Pooja Needs', 'Cleaning & Dust Cloth',
       'Rice Flour', 'Maida', 'Organic Flours', 'Regular Pasta',
       'Organic Salt,Sugar & Jaggery', 'Bottle & Tin Openers',
       'Whole Grains', 'Hand Wash', 'Exotic Vegetables', 'Shampoo',
       'Chinese Noodles', 'Olive Oils', 'Liquid Detergent',
       'Hair Colors & Dyes', 'Shaving Blade & Razors',
       'Ice Creams & Desserts', 'Vinegar', 'Ladles & Spatulas',
       'Ready Mix', 'Aluminium Foil & Cling Wrap',
       'Muffins, Cookies & Rusk', 'Packaged Drinking Water', 'Agarbatti',
       'Bakery & Breads', 'Other Spreads', 'Face Cream',
       'Healthy & Digestive Biscuits', 'Face Packs & Scrubs', 'Curd',
       'Cotton & Bandages', 'Oats', 'Honey', 'Toothpaste',
       'Organic Masalas & Spices', 'Rodent Control', 'Butter & Cream',
       'Ready Baking Mixes', 'Frozen Seafood', 'Mango Juices',
       'Pasta & Noodles', 'Biscuits', 'Ready To Eat & Cook',
       'Milk Drinks', 'Tissue Paper & Napkins', 'Lip Care',
       'Organic Dals & Pulses', 'Rasagulla & Gulab Jamun',
       'Facial Tissues', 'Milk', 'Salty Biscuits', 'Ice Cream',
       'Cooking Sauce', 'Organic Dry Fruits', 'Veg & Fruit',
       'Phenyles & Acids', 'Mustard Oils', 'Home & Air Freshener',
       'Pain Relievers', 'Organic Branded Foods', 'Flakes', 'Mouthwash',
       'Mens Deo', 'Toilet Cleaners', 'Jams & Sauces', 'Ayurvedic',
       'Soup', 'Ayurvedic Food', 'Sanitary Pads', 'Cutlery',
       'Tomato Sauce', 'Vanaspati', 'Other Jams', 'Pet Food',
       'Hand Sanitizer', 'Floor Cleaners', 'Frozen Veg Food',
       'Pre & Post Wash Care', 'Baking Ingredients', 'Glass Cleaners',
       'CFLs,cfls,7832553,2,0\r\n7831582,Channa Dal,channa-dal,7832491,2,0\r\n7832360,Cheese,cheese,7832363,2,0\r\n7831689,Chewing Gum,chewing-gum,7831685,2,0\r\n7832047,ChildrenS Books',
       'Frozen Chicken', 'Toilet Cleaning', 'Brushes & Scrubbers',
       'Brooms & Dust Pans', 'Toffee & Candy', 'Energy Drinks',
       'Other Pickle', 'Buttermilk', 'Other Juices', 'Other Soft Drinks',
       'Car Shampoo & Wax', 'Antiseptics', 'Grooming', 'Energy Powders',
       'Organic Juices', 'Soups', 'Baby Cereal', 'Baby Care Accessories',
       'Beverages', 'Foot Care', 'Snacks & Sweets', 'Organic Baby Foods',
       'Exam Boards', 'Car Freshener', 'Scissors, Glue & Tape',
       'Womens Deo', 'Office Stationery', 'Ready Masalas', 'Body Wash',
       'Fertilizers & Pesticides', 'Paneer & Tofu',
       'Organic Breakfast Cereals', 'Green Tea', 'Drain Cleaners',
       'Toilet Paper', 'Groundnut Oils', 'Mixed Fruit Jam',
       'Fryums & Papad', 'Disposable Plates & Utensils', 'Containers',
       'Colours', 'Cutters, Peelers & Scrapers', 'Battery', 'Chocolate',
       'Tea', 'Festive Gift Packs', 'Organic Edible Oils & Ghee',
       'After Shave', 'Dairy & Cheese', 'Heat & Eat Ready Meals',
       'Festive Gift Pack', 'Mukhwas & Mouth Freshener', 'Sanitary Aids',
       'Pens', 'Mango Pickle', 'Magazine',
       'Printer Cartridges & Printing Paper', 'Body Lotion', 'Talc',
       'Eye Care & Kajal', 'Cookery Books', 'Dishwash Liquids & Pastes'],
      dtype=object)

In [9]:
set_columns[0:5]

array(['Other Sauces', 'Cashews', 'Other Dals', 'Namkeen', 'Sugar'],
      dtype=object)

In [10]:
data = []
for member in members:
    selected_member = basket[basket["Member"] == member]
    for item in set_columns:
        finder = (selected_member[selected_member["Description"] == item])
        if(finder.shape[0]>=1):
            data.append(1)
        if(finder.shape[0]<=0):
            data.append(0)

In [11]:
len(data)

22896

In [12]:
len(set_columns)

216

In [13]:
len(members)

106

In [14]:
len(set_columns)*len(members)

22896

In [15]:
# this array is 1D
data[0:15]

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [16]:
# convert 1D array to 2D with 216 number columns for items, 106 number of rows for members
array = np.array(data)
array = array.reshape(-1,216)

In [17]:
array[0]

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### Create data frame from this data

In [18]:
MyBasket = pd.DataFrame({"Members":members})

Add items and their corseponding values for customers or members

In [19]:
MyBasket[set_columns] = array

C:\Users\Sakhi Larik\AppData\Local\Temp\ipykernel_20600\2913737793.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  MyBasket[set_columns] = array
C:\Users\Sakhi Larik\AppData\Local\Temp\ipykernel_20600\2913737793.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  MyBasket[set_columns] = array
C:\Users\Sakhi Larik\AppData\Local\Temp\ipykernel_20600\2913737793.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  MyBasket[set_columns] = array
C:\Users\Sakhi Larik\AppData\Local\Temp\ipykernel_20600\2913737793.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  MyBasket[set_columns] = array
C:\Users\Sakhi Larik\AppData\Local\Temp\ipykernel_20600\2913737793.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  MyBasket[set_columns] = array
C:\Users\Sakhi Larik\AppData\Local\Temp\ipykernel_20600\2913737793.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  MyBasket[set_columns] = array
C:\Users\Sakhi Larik\AppData\Local\Temp\ipykernel_20600\2913737793.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  MyBasket[set_columns] = array
C:\Users\Sakhi Larik\AppData\Local\Temp\ipykernel_20600\2913737793.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  MyBasket[set_columns] = array
C:\Users\Sakhi Larik\AppData\Local\Temp\ipykernel_20600\2913737793.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  MyBasket[set_columns] = array
C:\Users\Sakhi Larik\AppData\Local\Temp\ipykernel_20600\2913737793.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  MyBasket[set_columns] = array
C:\Users\Sakhi Larik\AppData\Local\Temp\ipykernel_20600\2913737793.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  MyBasket[set_columns] = array
C:\Users\Sakhi Larik\AppData\Local\Temp\ipykernel_20600\2913737793.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  MyBasket[set_columns] = array
C:\Users\Sakhi Larik\AppData\Local\Temp\ipykernel_20600\2913737793.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  MyBasket[set_columns] = array
C:\Users\Sakhi Larik\AppData\Local\Temp\ipykernel_20600\2913737793.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  MyBasket[set_columns] = array
C:\Users\Sakhi Larik\AppData\Local\Temp\ipykernel_20600\2913737793.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  MyBasket[set_columns] = array
C:\Users\Sakhi Larik\AppData\Local\Temp\ipykernel_20600\2913737793.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  MyBasket[set_columns] = array
C:\Users\Sakhi Larik\AppData\Local\Temp\ipykernel_20600\2913737793.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  MyBasket[set_columns] = array
C:\Users\Sakhi Larik\AppData\Local\Temp\ipykernel_20600\2913737793.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  MyBasket[set_columns] = array
C:\Users\Sakhi Larik\AppData\Local\Temp\ipykernel_20600\2913737793.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  MyBasket[set_columns] = array
C:\Users\Sakhi Larik\AppData\Local\Temp\ipykernel_20600\2913737793.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  MyBasket[set_columns] = array
C:\Users\Sakhi Larik\AppData\Local\Temp\ipykernel_20600\2913737793.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  MyBasket[set_columns] = array
C:\Users\Sakhi Larik\AppData\Local\Temp\ipykernel_20600\2913737793.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  MyBasket[set_columns] = array
C:\Users\Sakhi Larik\AppData\Local\Temp\ipykernel_20600\2913737793.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  MyBasket[set_columns] = array
C:\Users\Sakhi Larik\AppData\Local\Temp\ipykernel_20600\2913737793.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  MyBasket[set_columns] = array
C:\Users\Sakhi Larik\AppData\Local\Temp\ipykernel_20600\2913737793.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  MyBasket[set_columns] = array
C:\Users\Sakhi Larik\AppData\Local\Temp\ipykernel_20600\2913737793.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  MyBasket[set_columns] = array
C:\Users\Sakhi Larik\AppData\Local\Temp\ipykernel_20600\2913737793.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  MyBasket[set_columns] = array
C:\Users\Sakhi Larik\AppData\Local\Temp\ipykernel_20600\2913737793.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  MyBasket[set_columns] = array
C:\Users\Sakhi Larik\AppData\Local\Temp\ipykernel_20600\2913737793.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  MyBasket[set_columns] = array
C:\Users\Sakhi Larik\AppData\Local\Temp\ipykernel_20600\2913737793.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  MyBasket[set_columns] = array
C:\Users\Sakhi Larik\AppData\Local\Temp\ipykernel_20600\2913737793.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  MyBasket[set_columns] = array
C:\Users\Sakhi Larik\AppData\Local\Temp\ipykernel_20600\2913737793.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  MyBasket[set_columns] = array
C:\Users\Sakhi Larik\AppData\Local\Temp\ipykernel_20600\2913737793.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  MyBasket[set_columns] = array
C:\Users\Sakhi Larik\AppData\Local\Temp\ipykernel_20600\2913737793.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  MyBasket[set_columns] = array
C:\Users\Sakhi Larik\AppData\Local\Temp\ipykernel_20600\2913737793.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  MyBasket[set_columns] = array
C:\Users\Sakhi Larik\AppData\Local\Temp\ipykernel_20600\2913737793.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  MyBasket[set_columns] = array
C:\Users\Sakhi Larik\AppData\Local\Temp\ipykernel_20600\2913737793.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  MyBasket[set_columns] = array
C:\Users\Sakhi Larik\AppData\Local\Temp\ipykernel_20600\2913737793.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  MyBasket[set_columns] = array
C:\Users\Sakhi Larik\AppData\Local\Temp\ipykernel_20600\2913737793.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  MyBasket[set_columns] = array
C:\Users\Sakhi Larik\AppData\Local\Temp\ipykernel_20600\2913737793.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  MyBasket[set_columns] = array
C:\Users\Sakhi Larik\AppData\Local\Temp\ipykernel_20600\2913737793.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  MyBasket[set_columns] = array
C:\Users\Sakhi Larik\AppData\Local\Temp\ipykernel_20600\2913737793.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  MyBasket[set_columns] = array
C:\Users\Sakhi Larik\AppData\Local\Temp\ipykernel_20600\2913737793.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  MyBasket[set_columns] = array
C:\Users\Sakhi Larik\AppData\Local\Temp\ipykernel_20600\2913737793.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  MyBasket[set_columns] = array
C:\Users\Sakhi Larik\AppData\Local\Temp\ipykernel_20600\2913737793.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  MyBasket[set_columns] = array
C:\Users\Sakhi Larik\AppData\Local\Temp\ipykernel_20600\2913737793.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  MyBasket[set_columns] = array
C:\Users\Sakhi Larik\AppData\Local\Temp\ipykernel_20600\2913737793.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  MyBasket[set_columns] = array
C:\Users\Sakhi Larik\AppData\Local\Temp\ipykernel_20600\2913737793.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  MyBasket[set_columns] = array
C:\Users\Sakhi Larik\AppData\Local\Temp\ipykernel_20600\2913737793.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  MyBasket[set_columns] = array
C:\Users\Sakhi Larik\AppData\Local\Temp\ipykernel_20600\2913737793.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  MyBasket[set_columns] = array
C:\Users\Sakhi Larik\AppData\Local\Temp\ipykernel_20600\2913737793.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  MyBasket[set_columns] = array
C:\Users\Sakhi Larik\AppData\Local\Temp\ipykernel_20600\2913737793.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  MyBasket[set_columns] = array

In [20]:
MyBasket.shape

(106, 217)

In [21]:
MyBasket.head()

,Members,Other Sauces,Cashews,Other Dals,Namkeen,Sugar,Banana,Sugar Cubes,Other Sweets,Other Rice Products,...,Sanitary Aids,Pens,Mango Pickle,Magazine,Printer Cartridges & Printing Paper,Body Lotion,Talc,Eye Care & Kajal,Cookery Books,Dishwash Liquids & Pastes
0,M09736,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
1,M39021,0,0,1,1,1,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
2,M47229,0,1,1,0,1,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,M76390,0,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
4,M77779,0,1,1,1,1,1,0,1,1,...,0,0,0,0,0,0,0,0,0,0

We usually need to do hot encoding in order to set all values in either 0 or 1
* if value of an item >= 1 it is 1
* if value of an item <= 0 it is 0

But our data is already set for this

In [28]:
basket_set = MyBasket.drop(columns=["Members"])
basket_set.head()

,Other Sauces,Cashews,Other Dals,Namkeen,Sugar,Banana,Sugar Cubes,Other Sweets,Other Rice Products,Utensil Scrub Pads,...,Sanitary Aids,Pens,Mango Pickle,Magazine,Printer Cartridges & Printing Paper,Body Lotion,Talc,Eye Care & Kajal,Cookery Books,Dishwash Liquids & Pastes
0,1,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
1,0,0,1,1,1,0,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
2,0,1,1,0,1,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3,0,1,1,1,1,1,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
4,0,1,1,1,1,1,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0

In [24]:
encoder = TransactionEncoder()

In [31]:
encodedData = encoder.fit_transform(basket_set)

IndexError: index 106 is out of bounds for axis 0 with size 106

## Do Machine Learning Now Generate Frequent Itemset

In [27]:
freq_item = apriori(basket_set,min_support=0.5,use_colnames=True)

c:\Users\Sakhi Larik\AppData\Local\Programs\Python\Python311\Lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:110: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

:

In [ ]:
freq_item.head()

### Generate and Apply Rules

In [ ]:
rules = association_rules(freq_item,metric="lift",min_threshold=1)

In [ ]:
rules.head()