In [1]:
# importing module
import pandas as pd
import plotly.express as px
import numpy as np
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

In [2]:
# dataset
data = pd.read_csv("../data/Market_Basket_Optimisation.csv")
# printing the shape of the dataset
data.shape

(7500, 20)

In [3]:
# printing the heading
data.head()

,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
0,burgers,meatballs,eggs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,chutney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,turkey,avocado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,mineral water,milk,energy bar,whole wheat rice,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,low fat yogurt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
# Gather All Items of Each Transactions into Numpy Array
transaction = []
for i in range(0, data.shape[0]):
    for j in range(0, data.shape[1]):
        transaction.append(data.values[i,j])

In [5]:
# converting to numpy array
transaction = np.array(transaction)
#  Transform Them a Pandas DataFrame
df = pd.DataFrame(transaction, columns=["items"]) 
# Put 1 to Each Item For Making Countable Table, to be able to perform Group By
df["incident_count"] = 1 
#  Delete NaN Items from Dataset
indexNames = df[df['items'] == "nan" ].index
df.drop(indexNames , inplace=True)
# Making a New Appropriate Pandas DataFrame for Visualizations  
df_table = df.groupby("items").sum().sort_values("incident_count", ascending=False).reset_index()
#  Initial Visualizations
df_table.head(10).style.background_gradient(cmap='Greens')

In [6]:
# to have a same origin
df_table["all"] = "all" 
# creating tree map using plotly
fig = px.treemap(df_table.head(30), path=['all', "items"], values='incident_count',
                  color=df_table["incident_count"].head(30), hover_data=['items'],
                  color_continuous_scale='Greens',
                )
# ploting the treemap
fig.show()

In [7]:
# initializing the transactionEncoder
te = TransactionEncoder()
te_ary = te.fit(transaction).transform(transaction)
dataset = pd.DataFrame(te_ary, columns=te.columns_)
# dataset after encoded
dataset

,,&,a,b,c,d,e,f,g,h,...,p,r,s,t,u,v,w,x,y,z
0,False,False,False,True,False,False,True,False,True,False,...,False,True,True,False,True,False,False,False,False,False
1,False,False,True,True,False,False,True,False,False,False,...,False,False,True,True,False,False,False,False,False,False
2,False,False,False,False,False,False,True,False,True,False,...,False,False,True,False,False,False,False,False,False,False
3,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149995,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
149996,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
149997,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
149998,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
149999,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [13]:
# select top 50 items
first50 = df_table["items"][:50].values 
first50[:]

array(['mineral water', 'eggs', 'spaghetti', 'french fries', 'chocolate',
       'green tea', 'milk', 'ground beef', 'frozen vegetables',
       'pancakes', 'burgers', 'cake', 'cookies', 'escalope',
       'low fat yogurt', 'shrimp', 'tomatoes', 'olive oil',
       'frozen smoothie', 'turkey', 'chicken', 'whole wheat rice',
       'grated cheese', 'cooking oil', 'soup', 'herb & pepper', 'honey',
       'champagne', 'fresh bread', 'salmon', 'brownies', 'avocado',
       'hot dogs', 'cottage cheese', 'tomato juice', 'butter',
       'whole wheat pasta', 'red wine', 'yogurt cake', 'light mayo',
       'ham', 'energy bar', 'energy drink', 'pepper', 'cereals',
       'vegetables mix', 'muffins', 'oil', 'french wine', 'fresh tuna'],
      dtype=object)

In [15]:
# Extract Top50
dataset = dataset.iloc[:50]
# shape of the dataset
dataset.shape

(50, 27)

In [16]:
dataset

,,&,a,b,c,d,e,f,g,h,...,p,r,s,t,u,v,w,x,y,z
0,False,False,False,True,False,False,True,False,True,False,...,False,True,True,False,True,False,False,False,False,False
1,False,False,True,True,False,False,True,False,False,False,...,False,False,True,True,False,False,False,False,False,False
2,False,False,False,False,False,False,True,False,True,False,...,False,False,True,False,False,False,False,False,False,False
3,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
6,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
10,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
11,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
12,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
13,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
14,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
15,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
16,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
17,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
18,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
19,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,True,False,True,False,False,True,...,False,False,False,True,True,False,False,False,True,False
21,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
22,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
23,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
24,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
25,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
26,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
27,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
28,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
29,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
30,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
31,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
32,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
33,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
34,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
35,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
36,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
37,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
38,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
39,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
40,False,False,False,False,False,False,True,False,False,False,...,False,True,False,True,True,False,False,False,True,False
41,False,False,True,False,True,True,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
42,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
43,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
44,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
45,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
46,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
47,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
48,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
49,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [17]:
# Extracting the most frequest itemsets via Mlxtend.
# The length column has been added to increase ease of filtering.
frequent_itemsets = apriori(dataset, min_support=0.01, use_colnames=True)
frequent_itemsets['length'] = frequent_itemsets['itemsets'].apply(lambda x: len(x))
# printing the frequent itemset
frequent_itemsets

     support               itemsets  length
0       0.92                    (a)       1
1       0.04                    (b)       1
2       0.04                    (c)       1
3       0.02                    (d)       1
4       0.10                    (e)       1
..       ...                    ...     ...
374     0.02     (c, t, u, n, h, y)       6
375     0.02     (t, e, u, n, h, y)       6
376     0.02     (t, e, k, r, u, y)       6
377     0.02  (t, b, e, m, l, a, s)       7
378     0.02  (c, t, e, u, n, h, y)       7

[379 rows x 3 columns]

In [18]:
# printing the frequntly items 
frequent_itemsets[ (frequent_itemsets['length'] == 2) &
                   (frequent_itemsets['support'] >= 0.05) ]

    support itemsets  length
24     0.88   (a, n)       2
55     0.06   (s, e)       2
56     0.06   (t, e)       2
57     0.06   (u, e)       2

In [19]:
# printing the frequntly items with length 3
frequent_itemsets[ (frequent_itemsets['length'] == 3) ].head(3)

    support   itemsets  length
88     0.02  (a, e, b)       3
89     0.02  (a, l, b)       3
90     0.02  (a, m, b)       3

In [20]:
#  We set our metric as "Lift" to define whether antecedents & consequents are dependent our not
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1.2)
rules["antecedents_length"] = rules["antecedents"].apply(lambda x: len(x))
rules["consequents_length"] = rules["consequents"].apply(lambda x: len(x))
rules.sort_values("lift",ascending=False)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric,antecedents_length,consequents_length
2445,"(l, a)","(m, t, e)",0.02,0.02,0.02,1.000000,50.000000,0.0196,inf,1.000000,2,3
3373,"(h, y)","(u, e, n)",0.02,0.02,0.02,1.000000,50.000000,0.0196,inf,1.000000,2,3
3444,"(t, e, r)","(k, y)",0.02,0.02,0.02,1.000000,50.000000,0.0196,inf,1.000000,3,2
3443,"(k, t, e)","(r, y)",0.02,0.02,0.02,1.000000,50.000000,0.0196,inf,1.000000,3,2
3440,"(t, e, r, y)",(k),0.02,0.02,0.02,1.000000,50.000000,0.0196,inf,1.000000,4,1
...,...,...,...,...,...,...,...,...,...,...,...,...
98,(u),(s),0.06,0.06,0.02,0.333333,5.555556,0.0164,1.41,0.872340,1,1
96,(t),(s),0.06,0.06,0.02,0.333333,5.555556,0.0164,1.41,0.872340,1,1
97,(s),(t),0.06,0.06,0.02,0.333333,5.555556,0.0164,1.41,0.872340,1,1
18,(c),(e),0.04,0.10,0.02,0.500000,5.000000,0.0160,1.80,0.833333,1,1
19,(e),(c),0.10,0.04,0.02,0.200000,5.000000,0.0160,1.20,0.888889,1,1

In [21]:
# Sort values based on confidence
rules.sort_values("confidence",ascending=False)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric,antecedents_length,consequents_length
2445,"(l, a)","(m, t, e)",0.02,0.02,0.02,1.0,50.0,0.0196,inf,1.0,2,3
2375,"(c, a, d)","(o, v)",0.02,0.02,0.02,1.0,50.0,0.0196,inf,1.0,3,2
2364,(m),"(a, t, s, b)",0.02,0.02,0.02,1.0,50.0,0.0196,inf,1.0,1,4
3941,"(l, a, t)","(m, s, b)",0.02,0.02,0.02,1.0,50.0,0.0196,inf,1.0,3,3
2366,"(c, o, v, a)",(d),0.02,0.02,0.02,1.0,50.0,0.0196,inf,1.0,4,1
...,...,...,...,...,...,...,...,...,...,...,...,...
325,(e),"(c, n)",0.10,0.02,0.02,0.2,10.0,0.0180,1.225,1.0,1,2
1692,(e),"(k, r, t)",0.10,0.02,0.02,0.2,10.0,0.0180,1.225,1.0,1,3
320,(e),"(c, h)",0.10,0.02,0.02,0.2,10.0,0.0180,1.225,1.0,1,2
2475,(e),"(l, a, t, s)",0.10,0.02,0.02,0.2,10.0,0.0180,1.225,1.0,1,4
3034,(e),"(c, u, t, n)",0.10,0.02,0.02,0.2,10.0,0.0180,1.225,1.0,1,4